#!/usr/bin/env bash
# V6 baseline regeneration trigger: refresh generated artifacts after runtime admission landed.
set -euo pipefail

BRANCH="${BRANCH:-review/api-admission-batch-v6-foundation}"
BASELINE_SHA="${BASELINE_SHA:-1aaba357f46e83296419c1871fac3c28ea70dcff}"

if [[ -f docs/api-admission-batch-v6-verification.md ]]; then
  echo "V6 completion marker already exists; nothing to do."
  exit 0
fi

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

runtime_head="$(git rev-parse HEAD)"
tmp="$(mktemp -d "${RUNNER_TEMP:-/tmp}/tcg-v6.XXXXXX")"
trap 'rm -rf "$tmp"' EXIT

engine_identity() {
  node --import tsx --input-type=module -e 'import { engineIdentity } from "./scripts/engine-identity.ts"; console.log(JSON.stringify(engineIdentity()))'
}

tree_manifest() {
  find packages/wire/schemas tests/fixtures -type f -print0 |
    sort -z |
    xargs -0 sha256sum
}

echo "Runtime head: $runtime_head"
echo "Engine identity: $(engine_identity)"

mkdir -p "$tmp/preserved"
git archive "$BASELINE_SHA" tests/fixtures packages/wire/schemas | tar -xf - -C "$tmp/preserved"

echo "== V6 focused tests =="
node --import tsx --test --test-concurrency=1 --test-reporter=tap   tests/api-admission-batch-v6-source.test.ts   tests/api-admission-batch-v6-foundation.test.ts   tests/api-admission-batch-v6-gameplay.test.ts

echo "== In-repo source verification =="
node --import tsx scripts/verify-api-admission-batch-v6-source.ts --repo-root .

echo "== Preserved V5 replay compatibility =="
node --import tsx scripts/audit-replay-compatibility.ts "$tmp/preserved/tests/fixtures"

ordinary_generators=(
  generate-attack-condition-power-replay.ts
  generate-attack-ordered-effects-replay.ts
  generate-combat-attack-replay.ts
  generate-combat-resolution-replays.ts
  generate-combat-restrictions-replays.ts
  generate-combat-triggers-replays.ts
  generate-delayed-effects-replay.ts
  generate-demo-match-replay.ts
  generate-demo-setup-replay.ts
  generate-end-turn-history-replay.ts
  generate-field-legends-replay.ts
  generate-gear-capabilities-replay.ts
  generate-gear-replay.ts
  generate-goro-replay.ts
  generate-noncombat-replay.ts
  generate-overtime-replay.ts
  generate-private-information-replay.ts
  generate-react-replay.ts
  generate-reviewed-replay.ts
  generate-saburo-replay.ts
  generate-setup-replay.ts
  generate-targeted-defeat-replays.ts
  generate-targeted-spend-replay.ts
  generate-turn-replay.ts
  generate-value-conditions-replay.ts
  generate-wire-golden.ts
  generate-yorinobu-replay.ts
)

run_ordinary() {
  npm run contracts:export
  for script in "${ordinary_generators[@]}"; do
    echo "== $script =="
    node --import tsx "scripts/$script"
  done
  node --import tsx scripts/generate-reboot-multiplicity-replays.ts
  node --import tsx scripts/generate-reboot-multiplicity-replays.ts --check
}

echo "== Authoritative writer pass =="
# Generate each authoritative artifact once here. The normal PR validation suite
# is the final exact-commit verification gate after this workflow commits the
# regenerated tree, so do not duplicate every expensive writer in this bootstrap.
run_ordinary

echo "== Demo matrix =="
# The fixed 192-coordinate matrix is the expensive authoritative simulation pass.
# Use the generator's supported maximum parallelism for this one-time baseline
# refresh; the resulting traces are still consumed in deterministic coordinate order.
DEMO_MATRIX_CONCURRENCY=8 npm run test:matrix

echo "== Matrix-dependent reviews =="
node --import tsx scripts/review-reboot-multiplicity-matrix.ts
node --import tsx scripts/review-reboot-multiplicity-matrix.ts --check
node --import tsx scripts/review-demo-matrix-positions.ts
node --import tsx scripts/review-demo-matrix-positions.ts --check
npm run review:descriptor-v2
npm run review:descriptor-v2 -- --check

echo "== Final writer stability =="
tree_manifest > "$tmp/final.sha256"
npm run contracts:export
node --import tsx scripts/generate-reboot-multiplicity-replays.ts --check
node --import tsx scripts/review-reboot-multiplicity-matrix.ts --check
node --import tsx scripts/review-demo-matrix-positions.ts --check
npm run review:descriptor-v2 -- --check
tree_manifest > "$tmp/final-check.sha256"
diff -u "$tmp/final.sha256" "$tmp/final-check.sha256"

final_identity="$(engine_identity)"
changed_count="$(git status --short tests/fixtures packages/wire/schemas | wc -l | tr -d ' ')"

cat > docs/api-admission-batch-v6-verification.md <<EOF
# API Admission Batch V6 generated-baseline verification

This record was generated by the one-time V6 completion workflow.

- Runtime candidate: `$runtime_head`
- Preserved V5 baseline: `$BASELINE_SHA`
- Engine identity after V6 runtime change: `$final_identity`
- Generated fixture/schema paths changed before commit: `$changed_count`
- V6 source commit remains: `af9e0e1dd93b7eb77db5883bdd18809c8446d856`

Observed in the completion workflow:

- focused V6 source/foundation/gameplay tests executed successfully;
- the in-repo source verifier returned successfully;
- the preserved V5 replay compatibility audit returned successfully;
- wire schemas and every reviewed ordinary replay writer regenerated once;
- Reboot multiplicity generation/check completed before the final matrix;
- the complete fixed Demo matrix generated once from the reviewed deterministic schedule;
- Reboot matrix, Demo position, and Descriptor V2 reviews generated and checked against those trusted traces;
- a final non-simulation reader/check pass left the generated tree byte-identical.

This record does not replace hosted full unit, database integration, AI harness,
typecheck, lint, build, or card-validation gates. Those must pass on the exact
committed candidate after this workflow pushes its generated-baseline commit.
EOF

# Do not keep the one-time automation on the candidate tree.
rm .github/workflows/api-admission-batch-v6-complete.yml
rm .github/scripts/api-admission-batch-v6-complete.sh

git add -A
git diff --cached --check

if git diff --cached --quiet; then
  echo "No V6 completion changes to commit."
  exit 1
fi

remote_head="$(git ls-remote origin "refs/heads/$BRANCH" | awk '{print $1}')"
if [[ "$remote_head" != "$runtime_head" ]]; then
  echo "Branch moved from $runtime_head to $remote_head while regeneration was running; refusing to overwrite newer work."
  exit 0
fi

git commit -m "chore(v6): regenerate authoritative baseline" \
  -m "Regenerate wire schemas, replays, Demo matrix and dependent reviews for engine 0.4.0-api-admission-6 after replay-compatibility checks."

git push origin "HEAD:$BRANCH"
